{
 "title": "tasks_dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "state",
    "query": "pending, processing, done, failed"
   },
   { "name": "type", "query": "0,1,2,3,4,5,6,7,8,9" }
  ]
 },
 "panels": [
  {
   "title": "Tasks (--state)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count_tasks_by_state{state=~\"$state\"}",
     "legendFormat": "state: {{state}}"
    }
   ]
  },
  {
   "title": "Done tasks (--type)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "count_done_tasks_by_type{type=~\"$type\"}",
     "legendFormat": "type: {{type}}"
    }
   ]
  },
  {
   "title": "Total value (--type)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "total_value_done_tasks_by_type{type=~\"$type\"}",
     "legendFormat": "type: {{type}}"
    }
   ]
  },
  {
   "title": "Service state",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "service_up", "legendFormat": "{{job}}" }
   ]
  }
 ]
}