global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'producer'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['producer:6060']

  - job_name: 'consumer'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['consumer:6061']
